### ISSUE TITLE
IllegalArgumentException when trying to add a new file

### ISSUE THREAD

**Issue by Chris2011** [npetrovski/nbphar#3]
When I try to add a new file with the new file wizard, I got the following error:

```
java.lang.IllegalArgumentException: File cannot be null
    at name.npetrovski.jphar.Phar.<init>(Phar.java:50)
    at name.npetrovski.jphar.Phar.<init>(Phar.java:45)
    at name.npetrovski.nbphar.PharArchiveNode.<init>(PharArchiveNode.java:30)
    at name.npetrovski.nbphar.PharArchiveDataObject.createNodeDelegate(PharArchiveDataObject.java:84)
    at org.openide.loaders.DataObject$1.run(DataObject.java:372)
    at org.netbeans.modules.openide.util.DefaultMutexImplementation.readAccess(DefaultMutexImplementation.java:236)
    at org.netbeans.modules.openide.util.DefaultMutexImplementation$1R.run(DefaultMutexImplementation.java:1080)
    at org.netbeans.modules.openide.util.DefaultMutexImplementation.doWrapperAccess(DefaultMutexImplementation.java:1097)
    at org.netbeans.modules.openide.util.DefaultMutexImplementation.readAccess(DefaultMutexImplementation.java:226)
    at org.openide.util.Mutex.readAccess(Mutex.java:260)
    at org.openide.loaders.DataObject.getNodeDelegateImpl(DataObject.java:355)
    at org.openide.loaders.DataObject.getNodeDelegate(DataObject.java:342)
    at org.netbeans.modules.project.ui.TemplateChooserPanelGUI$FileChildren.createNodeForKey(TemplateChooserPanelGUI.java:424)
    at org.netbeans.modules.project.ui.TemplateChooserPanelGUI$FileChildren.createNodeForKey(TemplateChooserPanelGUI.java:403)
    at org.openide.nodes.ChildFactory.createNodesForKey(ChildFactory.java:120)
    at org.openide.nodes.AsynchChildren.createNodes(AsynchChildren.java:160)
    at org.openide.nodes.Children$Keys$KE.nodes(Children.java:1679)
[catch] at org.openide.nodes.ChildrenArray.nodesFor(ChildrenArray.java:149)
    at org.openide.nodes.EntrySupportDefault$Info.nodes(EntrySupportDefault.java:805)
    at org.openide.nodes.EntrySupportDefault.updateAdd(EntrySupportDefault.java:441)
    at org.openide.nodes.EntrySupportDefault.setEntries(EntrySupportDefault.java:295)
    at org.openide.nodes.EntrySupport.setEntries(EntrySupport.java:83)
    at org.openide.nodes.Children$Keys$2.run(Children.java:1573)
    at org.netbeans.modules.openide.util.DefaultMutexImplementation$1Exec.run(DefaultMutexImplementation.java:1016)
    at org.openide.nodes.Children$ProjectManagerDeadlockDetector.execute(Children.java:1938)
    at org.netbeans.modules.openide.util.DefaultMutexImplementation.postRequest(DefaultMutexImplementation.java:1022)
    at org.netbeans.modules.openide.util.DefaultMutexImplementation.postRequest(DefaultMutexImplementation.java:985)
    at org.netbeans.modules.openide.util.DefaultMutexImplementation.postWriteRequest(DefaultMutexImplementation.java:356)
    at org.openide.util.Mutex.postWriteRequest(Mutex.java:388)
    at org.openide.nodes.Children$Keys.applyKeys(Children.java:1582)
    at org.openide.nodes.Children$Keys.setKeys(Children.java:1526)
    at org.openide.nodes.AsynchChildren$1.add(AsynchChildren.java:190)
    at org.netbeans.modules.project.ui.TemplateChooserPanelGUI$FileChildren.createKeys(TemplateChooserPanelGUI.java:417)
    at org.openide.nodes.AsynchChildren.run(AsynchChildren.java:209)
    at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
    at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
    at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
    at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)
```

when I do nothing and close the wizard everything is fine, when I use the search field inside the new file wizard, it try to search for a filetype for example "ejs" which is not available, than the whole IDE is blocked by this error.

**Comment by Chris2011** [comment]
anything new here?
